name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: docker build . --file ./.devcontainer/Dockerfile --tag mpags-cpp:$(date +%Y.%m.%d)
      - name: Run "runtest" script
        run: docker run -v $PWD:/workspace --rm mpags-cpp:$(date +%Y.%m.%d) /workspace/runtest
